= aoc-2021

WARNING: Spoiler Alert! If you want to solve the aoc problems on your own, do not read any further.
This repository contains solutions for the problems in several languages.

NOTE: Result can be found on https://aoc-2021.netlify.com/[aoc-2021.netlify.com] powered by netlify.

In this repository, we will collect the code for the solutions of https://adventofcode.com[adventofcode] for the 2021 event.

If you want to join the discussions, here is the invitation for our https://join.slack.com/t/aoc-2021/shared_invite/zt-jpb3ukqo-t5amJownVL82CoRrrPNjEg[slack channel].

image::https://img.shields.io/badge/Slack-Invitation-orange.svg?style=for-the-badge[link=https://join.slack.com/t/aoc-2021/shared_invite/zt-jpb3ukqo-t5amJownVL82CoRrrPNjEg]

The slack channel itself is https://aoc-2021.slack.com/[aoc-2021]

The id of the https://adventofcode.com/2021/leaderboard/private/view/117454[shared leaderboard] is `117454-7d5aa225` .

== The Goal of this repository

... is to

- have a shared code base. It will be interesting to see how the same problem is solved in different languages with different approaches
- have a development environment in which all examples run out of the box

=== How do we ensure that all examples run out of the box?

If you open this repository with visual studio code and have the remote extension enabled, VS Code will detect the `.devcontainer` file and build a docker container which already contains execution environments for most popular languages.

If yours is missing, just add it via a pull request!

## Repository structure

The structure we start with is the following:

```
.
├── README.md
├── day01
├── day02
│   ├── groovy
│   |   └── rdmueller
│   |       ├── solution.groovy
│   |       └── description.adoc
│   └── [language]
│       └── [githubhandle]
│           ├── solution.[extension]
│           └── description.adoc
├── day03
├── day04
├── ...
```

== Documentation

As you can see in the above repository structure, each folder contains a `description.adoc`.
It would be great if everybody could explain their solution with a short description.

== Questions?

=> see you on Slack: https://aoc-2021.slack.com/[aoc-2021]
